// <auto-generated />
using EmartProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmartProject.Migrations
{
    [DbContext(typeof(SellerContext))]
    partial class SellerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmartProject.Models.Seller", b =>
                {
                    b.Property<int>("s_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bank_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("gstin")
                        .HasColumnType("float");

                    b.Property<string>("s_emailid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s_pwd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("s_id");

                    b.ToTable("Sellers");
                });
#pragma warning restore 612, 618
        }
    }
}
