// <auto-generated />
using EmartProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmartProject.Migrations.Buyer
{
    [DbContext(typeof(BuyerContext))]
    partial class BuyerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmartProject.Models.Buyer", b =>
                {
                    b.Property<int>("b_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("b_email_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("b_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("b_phn")
                        .HasColumnType("bigint");

                    b.Property<string>("b_pwd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("b_id");

                    b.ToTable("Buyers");
                });
#pragma warning restore 612, 618
        }
    }
}
